# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

os:
  - linux
  - osx

r:
  - 3.5
  - 3.6
  - release
  - devel

r_build_args: --no-build-vignettes
