# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

os:
  - linux
  - osx

r: bioc-devel

bioc_check: true

script:
    - R CMD BiocCheckGitClone .
    - R CMD build .
    - R CMD check *tar.gz --as-cran
    - R CMD BiocCheck ADImpute_2.1.0.tar.gz
